# Generated by Django 3.2.18 on 2023-04-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230420_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_user',
            new_name='like_users',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
